services:
  fastapi:
    image: "imagen-api"
    restart: unless-stopped
    container_name: "imagen-api"
    ports:
      - "3663:80"
    volumes:
      - /home/haizi/ej5hmh6w.default-esr:/code/profile1
      - /home/haizi/82sqdpek.default:/code/profile2
      - /home/haizi/nolimit-genai-img/app:/code/app
